### ISSUE TITLE
Aqara(Xiaomi) E1 Door & Window Sensor (MCCGQ14LM) not working

### ISSUE THREAD

**Issue by f45tb00t** [arendst/Tasmota-firmware#1]
Hello, 

I am using Tasmota v10.0.0(zbbridge) since today. I was with v9.4.0 before. Unfortunately the new Aqara devices are not working. 

It seems the firmware needs to be upgraded. 

Here are some references: 
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5403
https://github.com/Koenkk/zigbee2mqtt/issues/9274
https://github.com/home-assistant/core/issues/58985

@Theo: Is there anything you can do?

Kind regards

fb

**Comment by Jason2866** [comment]
Yes, wrong github for issues with Tasmota. Please open in https://github.com/arendst/Tasmota/discussions
