### ISSUE TITLE
Firmware for ESP32C2 4M/2M  with bluetooth.

### ISSUE THREAD

**Issue by miky2k** [arendst/Tasmota-firmware#10]
Feature request.
Thank

**Comment by Jason2866** [comment]
Will not be done in official firmwares. I am considering with an unofficial build.
For sure not for the c2 2M. Not enough flash.

**Comment by Jason2866** [comment]
MI32 and Bluetooth will be available in unofficial

**Comment by miky2k** [comment]
Program Version | 14.1.0.2 (ddf762b-bluetooth)
-- | --
2024-06-23T15:59:27
3_0_1/5.1.4.240602
0T00:00:55
26
16
Software reset CPU
 
SSId  xxxxxxxxxxxx  RSSI 54%, -73 dBmMode HT20Channel 6BSSId 70:4F:57:15:10:F9
 
tasmota-67BA9C-6812
fd6f:9ebf:407e:0:a3a:8dff:fe67:ba9c
fe80::a3a:8dff:fe67:ba9c%st1
08:3A:8D:67:BA:9C
192.168.120.118
192.168.120.1
255.255.255.0
192.168.120.1
0.0.0.0
 
Enabled
 
 
1883
Disabled
DVES_USER
DVES_67BA9C
tasmota_%06X
cmnd/tasmotas/
cmnd/tasmota_67BA9C/
cmnd/DVES_67BA9C_fb/
Disabled
 
None
 
6797980 (ESP32-C2 v1.0)
0x1640C8 (QIO)
4096 KB
4096 KB
1521 KB
1358 KB
57.0 KB (frag. 11%)
 
832 KB (used 77%)
2880 KB (used 52%)
320 KB

**Comment by miky2k** [comment]
![immagine](https://github.com/arendst/Tasmota-firmware/assets/6616232/9ec112e5-49e1-45f1-ab3d-e595fdd1cb7f)

**Comment by miky2k** [comment]
I should expect bluetooth config menu ?

**Comment by Jason2866** [comment]
`Setoption115 1`

EDIT: You are right. Need a change here https://github.com/Jason2866/Tasmota-build/blob/eeba26719f72bbe11e5fe6812d4a9bf5e7aab0f1/tasmota/tasmota_xdrv_driver/xdrv_79_esp32_ble.ino#L35

PR https://github.com/arendst/Tasmota/pull/21685
