### ISSUE TITLE
Please add esp32c3 firmware withbluetooth support.

### ISSUE THREAD

**Issue by wildblue** [arendst/Tasmota-firmware#2]
I had it working with version 10, but wantto upgrade my device.

**Comment by Jason2866** [comment]
See [https://tasmota.github.io/install/](https://tasmota.github.io/install/)

**Comment by wildblue** [comment]
I do not see a version for my ESP32 C3 with bluetooth at that link. Can you please verify that the binary is not Missing?

**Comment by Jason2866** [comment]
Choose Tasmota32 bluetooth in section inofficial.

**Comment by pearson** [comment]
Hi @Jason2866 . The "Tasmota 32 Bluetooth" firmware you're referring to will not work on the RISC-V based ESP32-C3. 

I've had to build my own ESP32-C3 firmware to get Bluetooth support. AFAIK there is no firmware in this repository that supports Bluetooth on the ESP32-C3. It would be nice to have one, though -- especially with Espressif moving away from Tensilica cores and [using RISC-V cores exclusively](https://www.eenewseurope.com/en/espressif-moves-exclusively-to-risc-v/).

**Comment by Jason2866** [comment]
It is here https://github.com/tasmota/install/blob/main/firmware/unofficial/tasmota32c3-bluetooth.factory.bin
@pearson
