### ISSUE TITLE
problem using "sonoff th elite" THR316D display

### ISSUE THREAD

**Issue by jesuisjct** [arendst/Tasmota-firmware#8]
I want to use tasmota on "sonoff th elite" THR316D according the parameters on this page
https://templates.blakadder.com/sonoff_THR316D.html

Everything works fine except the display.
I am using latest tasmota version.

"sonoff th elite" has a TM1621 display.

If I use tasmota32.bin firmware, I can select the GPIO parameters for TM1621. (the values for TM1621 appeared in the GPIO drop list)
But in the console the display commands : displaymode, displaytext,..  are not available.

If I use tasmota32-display.bin firmware, then the display commands are available in the console.
But I cannot select the GPIO parameters for TM1621 (the values for TM1621 do not appeared in the GPIO dop list)

In both case I cannot use the display.

Any suggestions how to use the TM1621 display on sonoff th elite ?

Thanks in advance

**Comment by arendst** [comment]
You need ``tasmota32.bin``. The display code is embedded in the sonoff thr316d driver and is not supported as user controlled display. There are specific commands to control the representation of sensor data in addition to it's default behaviour.

If your display doesn't work make sure you've re-assembled the device correctly. The display contacts need to be inserted firmly to make contact. As an alternative for the template you could have used online auto configuration for full initial configuration of the THR316D and sensor.

**Comment by jesuisjct** [comment]
Thanks for your reply.
I will check the display contacts and use auto configuration.
